version: "3.8"
name: "bydgoszcz"

services:
  be:
    build:
      context: be
    container_name: be
    ports:
      - "80:80"
    environment:
      CONNECTION_STRING: mongodb://admin:password@localhost:27017/bydgoszcz?authSource=admin
    networks:
      - app_network
  db:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: bydgoszcz
    volumes:
      - mongodb_data:/data/db
      - type: bind
        source: db/init
        target: /docker-entrypoint-initdb.d
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
